SELECT * FROM Employees WHERE salary IS NULL;
SELECT * FROM Orders WHERE discount IS NOT NULL;
SELECT * FROM Products WHERE category IS NULL;
SELECT COUNT(*) AS total_null_managers FROM Employees WHERE manager_id IS NULL;
SELECT emp_id,name,IFNULL(salary,0) AS salary FROM Employees;
SELECT emp_id,name,IFNULL(bonus,1000) AS bonus FROM Employees;
SELECT order_id,customer_name,IFNULL(amount,500) AS amount FROM Orders;
SELECT product_name,IFNULL(stock,0) AS stock FROM Products;
SELECT emp_id,name,COALESCE(salary,bonus) AS earnings FROM Employees;
SELECT emp_id,name,COALESCE(salary,bonus,0) AS income FROM Employees;
SELECT product_name,COALESCE(price,1000) AS final_price FROM Products;
SELECT customer_name,COALESCE(amount,discount,0) AS payment FROM Orders;
SELECT emp_id,name,NULLIF(salary,0) AS salary FROM Employees;
SELECT order_id,NULLIF(discount,0) AS discount FROM Orders;
SELECT amount/NULLIF(discount,0) AS result FROM Orders;
SELECT order_id,NULLIF(coupon_code,'DISC10') AS coupon_code FROM Orders;
SELECT emp_id,name,IFNULL(salary,0)+IFNULL(bonus,0) AS total_earnings FROM Employees;
SELECT * FROM Employees WHERE salary IS NULL AND bonus IS NULL;
SELECT * FROM Products WHERE price IS NULL AND category IS NOT NULL;
SELECT * FROM Orders WHERE amount IS NULL AND discount IS NULL;
SELECT emp_id,name,COALESCE(salary,bonus,1000) AS income FROM Employees;
SELECT order_id,NULLIF(discount,0) AS discount FROM Orders;
SELECT order_id,customer_name,IFNULL(amount,0)-IFNULL(discount,0) AS final_amount FROM Orders;
SELECT * FROM Employees WHERE salary IS NULL AND manager_id IS NOT NULL;